export const AUDIT_PLACES = {
  path: "browse",
  category: "browse",
  hotlink: "hotlinks",
  person: "people",
  request: "requests",
  publisher: "publishers",
  publishers: "publishers",
  platform: "platforms",
  platforms: "platforms",
  language: "languages",
  languages: "languages",
  interface: "interfaces",
  interfaces: "interfaces",
  architecture: "architectures",
  architectures: "architectures",
  filetype: "filetypes",
  filetypes: "filetypes",
  processor: "processors",
  processors: "processors",
};
